### ISSUE TITLE
Système de versionning (enfant -> parent)

### ISSUE THREAD

**Issue by Aakodal** [readthedocs-fr/bin-server#10]
Il sera possible sur chaque snippet de faire une "révision" de celui-ci, c'est à dire une version modifiée/corrigée de celui-ci. Chaque snippet sera donc relié à son parent via un lien cliquable sur l'interface.

Les limitations de Redis font qu'il sera difficile d'établir une relation entre un snippet et ses révisions (lister les différentes révisions du snippet), et nous avons donc décidé dans un premier temps de ne pas implémenter cette fonctionnalité.

À faire : 
- [ ] Back : ajouter l'id du parent dans le hash du snippet dans la bdd
- [ ] Front : ajouter un lien cliquable/bouton qui ferait une requête GET sur `/<parent id>`
- [ ] Front : ajouter un bouton pour créer une nouvelle révision d'un snippet existant

**Comment by bacddd** [comment]
Il faut bien récupérer le contenu de l'ancien paste et l'ajouter à un nouveau qui soit modifiable?
(je demande car j'ai commencé mais en essayant de faire rééditer le snippet )

**Comment by Julien00859** [comment]
Oui c'est bien ça, donc modifier le template `newform.html` qu'on puisse injecter du texte pré-défini dans la textarea et choper le code depuis redis.
