### ISSUE TITLE
Problème d'encodage

### ISSUE THREAD

**Issue by Iltotore** [readthedocs-fr/bin-server#100]
Bonjour,
les accents/caractères non-ASCII semblent ne pas passer correctement sur le paste.

Par exemple, le message `éléphant` donne: https://bin.readthedocs.fr/ordien.txt

**Comment by Mesteery** [comment]
Ha, c'est nouveau ce bug

**Comment by Julien00859** [comment]
C'est un bug qui vient de mon refactoring quand j'ai tout passé en utf-8, on dirait qu'il reste encore du latin-1 dégueu qqpart, voila deux jours que j'essaie de reproduire le problème avec des tests unitaires mais rien n'y fait. Je vais finir par lancer un wireshark pour voir ce qui passe concrètement sur le réseau.

Merci d'avoir remonter le problème !

**Comment by Mesteery** [comment]
Je pense pas que ça vient du latin-1, car même en créant un nouveau bin, le bug est présent
