### ISSUE TITLE
Packaging Pypi

### ISSUE THREAD

**Issue by Julien00859** [readthedocs-fr/bin-server#112]
Pour le moment je fais la packaging sur Pypi manuellement, j'aimerais automatiser le processus via l'intégration continue. Juste avant qu'une PR est mergée, il faudrait recommiter pour changer le fichier VERSION en fonction du titre du commit ou (prioritaire) d'un tag présent sur la PR.

Pour un commit `fix` on incrémente BUILD, pour les autres commits on incrémente MINOR. Si le tag "Breaking change" (qui est à créé) existe sur la PR on doit incrémenter MAJOR.

Pour le moment le package est sauvegardé via mon propre compte, je n'ai pas tellement de problème à ce qu'on le réhéberge avec un compte "officiel" readthedocs. Pour le moment la commande que j'utilise pour uploader un package sur pypi est la suivante:

    $ python3 -m twine upload dist/rtd_bin_server-1.0.0-py3-none-any.whl

Et twine me prompt pour mon username/password. Il faudrait investiguer pour ne pas être prompt voire mieux utiliser une clé d'api.

**Comment by Mesteery** [comment]
> Et twine me prompt pour mon username/password. Il faudrait investiguer pour ne pas être prompt voire mieux utiliser une clé d'api.

Concernant le prompt, on peut spécifier l'username/password dans les variables d'environnement.
Twine ne permet pas de s'authentifier via un token pour le moment.

**Comment by Julien00859** [comment]
Ouais donc il va falloir qu'on crée un compte pour rtdbin :/
