### ISSUE TITLE
Ajouter un guide à la page d'acceuil

### ISSUE THREAD

**Issue by zazbone** [readthedocs-fr/bin-server#114]
Hello !

Un petit manuel d'utilisation sur la page par défaut du bin permettrait d'éviter d'expliquer aux nouveaux comment l'utiliser

Quand on redirige les nouveaux sur le bin pour les codes longs, il faut souvent leur expliquer le fonctionnement du bin
Le manuel n'aurai pas besoin d'être long. Simplement un peu plus long que le "Entrez votre code" actuel

Exemple:
> Copier coller votre code ici
Cliquez sur le bouton bleu "enregistré" en bas à droite
Et partager l'adresse de la page

Merci :heart:

**Comment by Mesteery** [comment]
Cela se fait assez facilement si tu veux le faire.
https://github.com/readthedocs-fr/bin-server/blob/9cfa02e7f722c91a128729c717749018c23eade9/bin/views/newform.html#L9
Il suffit d'ajouter dans l'attribut `placeholder`.
Pour les sauts de ligne, tu as 2 moyens, soit tu fais un saut de ligne dans le fichier (moche)
```html
            <textarea spellcheck=false placeholder="A.
B.
C." name=code autofocus required>{{code}}</textarea> 
```
soit (mieux) :
```html
            <textarea spellcheck=false placeholder="{{"\n".join(["A.", "B.", "C."])}}" name=code autofocus required>{{code}}</textarea> 
```

**Comment by zazbone** [comment]
Je peux rédiger et pr
Mais s'il je testes avant il va me falloir plus de temps :monkey:

**Comment by Mesteery** [comment]
> Mais s'il je testes avant il va me falloir plus de temps 🐒

Pour tester à la limite, t'as juste besoin de Python, pas besoin de Redis, il suffit juste de regarder si la page `/` a correctement été générée avec le bon placeholder !

**Comment by Julien00859** [comment]
Je serais même d'avis d'avoir une explication plus complète, genre expliquer ce qu'est un bin, ...

Alors comme mestery l'à laissé entendre un plateholder multiligne ça va rendre dégueu dans le code source mais plutôt que de passer par du code interprété, je pense plutôt qu'on pourrait utiliser une directive bottle pour aller importer un autre fichier, on pourrait avoir un template `placeholder.txt` à `% include`

**Comment by zazbone** [comment]
Ha c'est ce que je voulais savoir quand j'ai demander si on pouvais link un fichier txt dans de l'html :')
Oui, moin ya de texte dans du code mieu c'est
