### ISSUE TITLE
Auto release

### ISSUE THREAD

**Issue by Mesteery** [readthedocs-fr/bin-server#121]
Pour automatiser les releases, nous pouvons utiliser GitHub Actions avec https://github.com/googleapis/release-please et https://github.com/pypa/gh-action-pypi-publish.

Nous devrons aussi suivre [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
Il faudra aussi ne pas oublier à mettre à jour le *How to contribute* (#120).

**Comment by Julien00859** [comment]
Tu as raison, elle est pas très belle cette issue... Qu'est-ce que se dirait @fusetim si il voyait ça en comparaison de #18
