### ISSUE TITLE
Possibilité de changer le langage du bin par l'UI.

### ISSUE THREAD

**Issue by enimaloc** [readthedocs-fr/bin-server#135]
On pourrait ajouter la fonctionnalité de changer le langage du bin directement via une liste comme pour créer un bin, cela pourrait améliorer l'utilisation sur les mobiles, car quand on ouvre un bin sur téléphone celui si vas s'ouvrir dans le navigateur interne de Discord ce qui nous offre pas la possibilité de modifier l'url la seule façon à ce moment là c'est d'ouvrir, le bin dans le navigateur externe, et cela permettrais d'éviter que l'utilisateur met un langage non supporté par le serveur.

**Comment by Mesteery** [comment]
Je trouve qu'il n'y a aucun intérêt à ça, vu que déjà le créateur du bin *a choisi* le bon langage. Et puis même si jamais tu veux changer pour je ne sais quel raison, c'est pas si chiant que ça d'ouvrir dans le navigateur sur mobile.

**Comment by Julien00859** [comment]
Il s'avère que 90% des bins sont créé au format plaintext, donc 90% du temps il faut changer l'extension dans l'URL, je suis d'avis qu'on pourrait simplifier l'expérience utilisateur

**Comment by Mesteery** [comment]
90% ?

**Comment by Julien00859** [comment]
$ journalctl -u gunicorn@bin.service | grep -o 'New .*' | cut -d ' ' -f2 | sort | uniq -c | sort -nr
         90 txt
         87 text
         41 python
         19 php
          6 javascript
          6 java
          6 html
          6 c
          5 py
          4 plaintext
          4 js
          3 typescript
          2 css
          1 weight
          1 ts
          1 solidity
          1 lisp
          1 JavaScript

**Comment by Mesteery** [comment]
64.43% en comptant `weight` et `solidity`.
Mais du coup, finalement, pourquoi pas :+1:.
