### ISSUE TITLE
(Discord) Bloc de code -> bin

### ISSUE THREAD

**Issue by Aakodal** [readthedocs-fr/bin-server#14]
Cette fonctionnalité se fera à l'aide d'un bot Discord, nommé [ReadTheBin](https://github.com/readthedocs-fr/read-the-bin).

Roadmap :
- [x] Gestion des blocs de code comportant au minimum 20 retours à la ligne (`\n`). Le message original est supprimé et un message identique est envoyé à l'aide d'un embed, remplaçant les blocs de code par les liens des bins.
- [x] Le message envoyé par le bot peut être supprimé par l'auteur du message originel, à l'aide d'une simple réaction.
- [x] Gestion des fichiers `message.txt` afin d'en récupérer les blocs de code et de les transformer en bin. Le fichier ne sera pas supprimé mais le bot essaiera tout de même de renvoyer son contenu en remplaçant les blocs de code par les liens des bins à l'aide d'un embed. Si la taille excède d'une manière ou d'une autre la limite imposée par Discord, le message ne sera constitué que des liens vers les bins.
- [x] Support des requêtes au service de bin
- [x] Liaison des requêtes à *rtd-bin* **(en attente de la mise en place dudit service)**

**Révision du 29/10/2020 à 01h00 :** Les webhooks seraient BEAUCOUP trop API-spammy et le bot se retrouverait rate-limit. Il en a été conclu que les embeds seront utilisés à la place.

---
Développeur assigné : @Aakodal

**Comment by NoeMastrorillo** [comment]
Je pense que tu peux faire un dossier bot pareillement au dossier bin où tu pourras dev le bot, ou alors il faudrait faire un autre repo pour pas mélanger les dépendances. À voir avec les autres.

**Comment by Aakodal** [comment]
> Je pense que tu peux faire un dossier bot pareillement au dossier bin où tu pourras dev le bot, ou alors il faudrait faire un autre repo pour pas mélanger les dépendances. À voir avec les autres.

C'est surtout que ce sont deux langages différents et deux projets différents.

**Comment by AntoineJT** [comment]
Cela irait probablement plutôt dans un bot du type boombot, mais pas forcément nommé comme ça
Il faudrait voir avec TnTakara à la rigueur, quitte à faire un bot spécialisé dans l'upload de bins, et plus tard, si on se retrouve avec plein de bots spécifiques à RtD, les remplacer par un bot unique du type boombot

**Edit:** Pour le moment faire un bot spécialisé semble une bonne solution, quitte à le faire évoluer ensuite en tant que bot multi-tâches spécifiques au serveur, type boombot

**Proposition de nom :** ReadTheBin

**Comment by NoeMastrorillo** [comment]
Mais du coup ça serait bien que tout le monde puisse aussi participer au bot. Tu le fais avec quel langage ?

**Comment by Aakodal** [comment]
> Mais du coup ça serait bien que tout le monde puisse aussi participer au bot. Tu le fais avec quel langage ?

TypeScript, le tout en reprenant un micro-framework basique mais qui fait le taf de ma conception. Ainsi je profite de l'expérience et des retours sur mon code pour améliorer mes compétences ainsi que ledit code (je ne dépend donc pas d'un framework tiers)

**Edit :** il sera bien évidemment open source et, si @AntoineJT me le permet, disponible sur l'organisation

**Comment by AntoineJT** [comment]
Qu'il soit disponible sur l'organisation est justement le but, je te ferai un dépôt quand tu en auras besoin

**Comment by Julien00859** [comment]
Autant je trouve ça normal que le code se trouve sur un projet à part, autant je trouve que les issue/pr/project devraient être communes. Le bot ne serait au final qu'un autre "client" au même titre que la page web et donc pourrait être hébergé directement ici.

**Comment by Aakodal** [comment]
J'avoue ne pas trop avoir compris ce que tu proposes ici

**Comment by Julien00859** [comment]
De mettre ton code dans un dossier de ce repo, même si c'est un sous-projet "à part" et qu'il aurait ses propre dépendances ça faciliterait la centralisation niveau issues/pull request/projet

**Comment by Aakodal** [comment]
Pourquoi pas. @AntoineJT ?

**Comment by Aakodal** [comment]
On pourrait donc voir la branche main comme ceci : 
.
|- rtd-bin/
ʟ read-the-bin/

avec rtd-bin/ le dossier pour le service de bins, et read-the-bin/ le code du bot

**Edit :** comme l'a proposé Tim, on peut également faire un système de "sous-module git", ainsi on retrouve le bot sur le repo bin, et peut-être inversement.

**Comment by Julien00859** [comment]
Let's only have dedicated folder for the source code and mixup the meta-files (python setuptools's `setup.py`, node npm's `package.json`) in the root folder. There will be just a few files mixed-up and on several repositories I see on github the root folder gets pretty bloated with all the external service configurations anyway soo...

    .
    |- bin/
    |-- views/
    |-- __init__.py
    |-- __main__.py
    |-- bin.py
    |- bot/
    |-- whatever.js
    |- README.md
    |- package.json
    |- setup.py

What do you think ?

**Comment by Aakodal** [comment]
Ce serait assez messed up, surtout quand dans la racine du bot t'as un dossier src/, les fichiers d'ESLint et de Prettier, le package et package-lock, le readme, et tous les fichiers .ignore

**Comment by Julien00859** [comment]
ouais le root serait messed-up mais de toute manière le root fini toujours par être complètement messed-up... un repo complètement tiré au hazard:

![2020-10-29_14-42-11](https://user-images.githubusercontent.com/8208953/97581589-0b2b4880-19f5-11eb-924a-d61b8610ccb1.png)

Tu pourrais faire un `tree` de ton côté qu'on voit l'ampleur des dégâts si on le fait comme je propose ?

**Comment by Julien00859** [comment]
@Aakodal je me permet de te ping ici vu que ton bot est mostly béta-tested. Aussi je me permets de rebump la discussion de peut-être mergé les deux repos. J'ai toujours dans l'idée qu'avoir les issues/pr à un seul endroit serait bénéfique (ce serait-ce que pour la communauté, un seul repo à partager tu vois ?), cf https://github.com/readthedocs-fr/bin/issues/14#issuecomment-718745388

**Comment by Aakodal** [comment]
Après niveau host par exemple, quand faut update un des deux services, bah faut pull l'intégralité des trucs

**Comment by Julien00859** [comment]
Si on inclue une stratégie de déploiement continue alors on n'a plus de problème. Aussi, le bot et le bin sont intrinsèquement liés, une modif pas backward-compatible avec le bot doit être fixé dans le bot également.

**Comment by Julien00859** [comment]
https://www.strawpoll.me/42333426

**Comment by Mesteery** [comment]
Perso je suis contre, c'est deux langages différents et ca serait compliqué niveau organisation je trouve
