### ISSUE TITLE
Switch to pyproject.toml?

### ISSUE THREAD

**Issue by Mesteery** [readthedocs-fr/bin-server#154]

**Comment by Julien00859** [comment]
The change would be trivial in the source code, what would not be trivial is to update every piece of documentation plus the CD pipeline to use [build](https://pypi.org/project/build/) instead of `python setup.py ...`. I'm not sure this repository would have an immediate benefit.

**Comment by Mesteery** [comment]
I thought it was easier. It would get rid of `version.txt` and have better `changelog-types` (release-please).
But I could add these changelog-types to have a more complete changelog : `[{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"perf","section":"Performance Improvements"},{"type":"deps","section":"Dependencies"},{"type":"revert","section":"Reverts"},{"type":"docs","section":"Documentation"},{"type":"style","section":"Styles","hidden":true},{"type":"chore","section":"Miscellaneous Chores","hidden":true},{"type":"refactor","section":"Code Refactoring","hidden":true},{"type":"test","section":"Tests","hidden":true},{"type":"build","section":"Build System","hidden":true},{"type":"ci","section":"Continuous Integration","hidden":true}]`
