### ISSUE TITLE
RFC 03 - Configuration

### ISSUE THREAD

**Issue by fusetim** [readthedocs-fr/bin-server#18]
# RFC 03 - Configuration

Ce document est une RFC (__Request for Comments__), toute critique est la
bienvenue à partir du moment où elle se veut constructive.

Statut du document : Proposition  
Dernière révision le : 30 octobre 2020 à 20 h 39 
Auteurs : FuseTim  

## Résumé

Nous énumérerons les différents moyens de mettre en place la configuration de
notre projet rtd-bin, service de pastebin de la communauté __Read The Docs__. 

## Contexte

Le service de rtd-bin doit communiquer avec plusieurs services, notamment le
service Redis qui sert de base de données et à un service de reverse-proxy afin
d'écouter les requêtes des différents utilisateurs du service.

Pour permettre la communication entre ces différents services, des couples
d'adresse IP-port et des identifiants de connexion doivent être renseignés. De
fait, ces informations doivent être renseignées par l'administrateur du système
et doivent donc être facilement modifiable et éviter d'être compromis. 

Également, peut-être soumis à une configuration la liste des langages et les
extensions de fichiers associées du bin. Bien que peu souvent modifiée, il
reste important de permettre à l'administrateur du service de le modifier
aisément.

## Divers moyens de configuration

Dans le monde, des programmes informatiques, il existe 3 grands moyens de
permettre la configuration d'un logiciel. Il semble approprié de les citer, et d'y 
chercher leurs inconvénients et avantages.

### Arguments en ligne de commande

__Exemple :__
```sh
$ python -m bin <arg1> [--opt1=value1]
```

Pour un nombre d'arguments relativement faible, l'utilisation d'arguments et
d'options en ligne de commande permet de facilement utiliser et configurer un
logiciel. Également, l'implémentation est simple si les arguments reste
raisonnable en nombre.

Toutefois l'utilisation des arguments en ligne de commande peut se révéler
fastidieuse lorsque les arguments sont multiples et également plus difficile à
automatiser. Également, l'utilisation de secret en argument est à éviter puisque
ceci sont visibles dans l'ensemble du système (ainsi que les processus enfants),
ce qui cause des risques de compromission.

### Variables d'environnement

__Exemple :__
```sh
$ KEY1=VALUE1 python -m bin
```

Les variables d'environnement est un moyen efficace de configurer un logiciel,
toutefois certaines limitations existent, notamment la compatibilité avec
Windows est plus difficile à réaliser puisqu'il n'existe que les variables
globales et les variables utilisateurs. De plus, l'utilisation d'objets, liste ou
map n'y 'est pas naturelle.

La compromission des variables d'environnement est moindre mais il faut noter
toutefois qu'elles se propagent aux processus enfants. Il est nécessaire d'y
faire particulièrement attention.

### Fichiers de configuration

__Exemple :__
```toml
listen = "localhost"
port = 8080
compress = true

[redis]
host = "localhost"
port = 6379
user = "my_user"
password = "..."
prefix = "rtd.bin"

#...
```

Le fichier de configuration est moyen particulièrement adapté à de nombreuses
variables et à de nombreux types de valeur (objets, listes, map, date, etc.).
Également, rien n'empêche la séparation des variables en plusieurs fichiers de
configuration, particulièrement utile pour de grande map clé-valeur.
Aussi, il reste convenable de les utiliser pour des secrets si leurs permissions d'accès
sont bien gérées.

Cependant l'utilisation de fichier de configuration oblige l'utilisation du
système de fichier, ce qui peut être embêtant lors de l'usage avec certains
environnements Docker. Également, il nécessite une nouvelle dépendance afin de
parcourir la configuration. Toutefois beaucoup de formats et d'implémentations
existent, ce qui offre une grande diversité dans le choix.

## Implémentation

L'implémentation choisie doit être discutée avec l'ensemble des
contributeurs potentiels. L'implémentation est cependant nécessaire pour
permettre la continuité du développement du projet __rtd-bin__.

**Comment by NoeMastrorillo** [comment]
Je pencherais pour le fichier de configuration, ça me paraît le plus pratique et polyvalent.

**Comment by Julien00859** [comment]
Je pencherais pour toujours passer par `os.getenv()`, ça fera une source unique de vérité à charger et le plus simple à packager avec un service sur linux : `EnvironmentFile=/etc/bin.conf`, docker a un fonctionnement similaire. On peut configurer l'application directement via la ligne de commande : `REDIS_DATABASE=localhost python3 -m bin`. On peut aussi configurer l'application via un fichier d'environnement qui serait chargé avec [python-dotenv](https://pypi.org/project/python-dotenv/), une simple option en cli pourrait suffire pour donner le chemin vers le fichier à charger : `python3 -m bin --config /etc/bin.conf`.

**Comment by Julien00859** [comment]
By the way, je viens de lire que 12-factors app conseillent de passer par les env pour gérer la config <https://12factor.net/config>
