### ISSUE TITLE
Problème : Les requêtes GET qui retournent des templates sont doublées

### ISSUE THREAD

**Issue by NoeMastrorillo** [readthedocs-fr/bin-server#19]
J'ai pu remarquer en faisant le système de longévité des snippets (en fonction du nombre d'utilisations) que les requêtes GET renvoyant des templates sont doublées.

### Comment reproduire le problème : 
- Lancer le serveur à l'aide de la commande `.\venv\Scripts\python -m bin` sur Windows ou `/venv/bin/python -m bin` sur Linux (en considérant que vous êtes à la racine du projet et que vous avez installé le serveur avec la commande `.\venv\Scripts\pip install -e .` sur Windows ou `/venv/bin/pip install -e .` sur Linux).
- Se connecter sur l'adresse `localhost:8080`.
- On peut déjà voir dans le terminal que la requête GET sur `/` qui renvoie la template de la création d'un nouveau snippet est appelée 2 fois : 
```
127.0.0.1 - - [30/Oct/2020 20:58:18] "GET / HTTP/1.1" 200 661                             <---
127.0.0.1 - - [30/Oct/2020 20:58:18] "GET /assets/css/style.css HTTP/1.1" 304 0
127.0.0.1 - - [30/Oct/2020 20:58:18] "GET / HTTP/1.1" 200 661                             <---
127.0.0.1 - - [30/Oct/2020 20:58:19] "GET /favicon.ico HTTP/1.1" 404 724
```
- On peut aussi noter que les requêtes GET sur les assets ne sont elles appelées qu'une fois. Je pense que c'est donc propre aux templates.
- Créer un nouveau snippet sur le site et l'envoyer
- On peut voir que la requête GET sur `/<id>` qui fournit la template du snippet est elle aussi appelée 2 fois : 
```
127.0.0.1 - - [30/Oct/2020 20:58:34] "POST /new HTTP/1.1" 303 0
127.0.0.1 - - [30/Oct/2020 20:58:34] "GET /raheve HTTP/1.1" 200 641          <--
127.0.0.1 - - [30/Oct/2020 20:58:34] "GET /raheve HTTP/1.1" 200 641          <--
```

Je sais pas trop d'où est-ce que ça peut venir c'est pour ça que je fais une issue et que je règle pas moi même le problème.

**Comment by Julien00859** [comment]
J'y regarde quand j'ai mergé @Acaretia

**Comment by NoeMastrorillo** [comment]
J'ai pu trouver un poste concernant non pas bottle mais flask mais ayant le même soucis, et ça pourrait venir des extensions de mon navigateur. Je testerai d'en enlever demain.

Le poste en question : https://stackoverflow.com/questions/59590884/why-the-get-request-in-flask-is-called-twice

**Comment by NoeMastrorillo** [comment]
J'ai désactivé toutes mes extensions mais ça n'a pas l'air de changer quelque chose. Pourtant avec curl j'ai bien qu'une seule requête GET, mais en même temps ça me le fait sur tous mes navigateurs, donc c'est propre aux navigateurs mais en même temps pas propre au navigateur... Est-ce que vous avez le même soucis vous ?

**Comment by NoeMastrorillo** [comment]
L'issue semble être partie avec le nouveau front, je sais pas du tout d'où ça pouvait venir mais c'est cool j'vais pouvoir avancer sur #5
