### ISSUE TITLE
Système d'unités de temps pour les valeurs de durées

### ISSUE THREAD

**Issue by NoeMastrorillo** [readthedocs-fr/bin-server#32]
Pour notamment la durée limite des snippet (#5), on a jugé utile d'avoir un système qui transformerait une unité de temps (par exemple `15min`) en secondes, un peu à la manière de [ce système].(https://gist.github.com/Julien00859/a63f6b830547059795689e549045853f)
Les différentes unités possibles seraient : 
- `s`: secondes
- `min`: minutes
- `h`: heures
- `d`: jours

**Comment by Julien00859** [comment]
Ce qui serait top serait d'en faire une lib qu'on pourait ajouter dans les dépendances, faudrait faire pareil pour mon gist

**Comment by NoeMastrorillo** [comment]
Du coup je mets les trucs dans un autre dossier que `bin/` ? genre `units/`

**Comment by Julien00859** [comment]
Je suis en train de faire un package avec mes trucs tkt ça arrive
https://gist.github.com/Julien00859/a63f6b830547059795689e549045853f
