### ISSUE TITLE
On pourrait faire un truc automatisé au niveau du backend au lieu de devoir mettre tous les langages qu'on a déjà mis dans les utils.

### ISSUE THREAD

**Issue by Julien00859** [readthedocs-fr/bin-server#37]
On pourrait faire un truc automatisé au niveau du backend au lieu de devoir mettre tous les langages qu'on a déjà mis dans les utils.

_Originally posted by @NoeXWolf in https://github.com/readthedocs-fr/bin/pull/35#issuecomment-735374062_

**Comment by Aakodal** [comment]
Je vais pas m'avancer dessus étant donné que j'ai aucune idée de comment faire, mais par contre faut faire gaffe aux noms des langages : tous ne sont pas composés d'une majuscule et du reste en minuscule (HTML, SQL, CSS, PHP, JavaScript...). Du coup, mon idée c'était de récupérer les langages dans l'utils en prenant dans le newform.html (je sais pas si c'est possible ?), vu que si on fait dans ce sens là, on n'a pas à se soucier des majuscules puisque tout finira en minuscules.

**Comment by NoeMastrorillo** [comment]
Oui mais dans le front y'a pas les extensions. Je pensais qu'on pourrait stocker les langages avec extension, nom de l'option et nom complet dans un fichier genre du json ou autre fichier de configuration, et on les récupère dans le front avec un script js qui va générer les options et dans le back dans les utils.

**Comment by Aakodal** [comment]
Si, le front a les extensions, c'est justement le `value=""` à chaque `<option>`

**Comment by NoeMastrorillo** [comment]
Je me suis trompé, c'est le nom brut des langages que highlight.js utilise qu'il manque dans le front.

**Comment by Aakodal** [comment]
> Je me suis trompé, c'est le nom brut des langages que highlight.js utilise qu'il manque dans le front.

AKA le nom affiché, en minuscules et les espaces retirés ? 👀

**Comment by NoeMastrorillo** [comment]
Ouais bon n'empêche que c'est dégueulasse de récupérer les langages via le front
