### ISSUE TITLE
Tabs support

### ISSUE THREAD

**Issue by Hokkaydo** [readthedocs-fr/bin-server#39]
Ce serait une feature intéressante que de supporter les tabulations dans le code.
Actuellement, il est possible d'indenter proprement son code sans le copier-coller ou utilisez la barre espace.

A propos de ça, il pourrait également être intéressant de pouvoir modifier la taille d'une tabulation d'indentation en bas de l'écran.

### Résumé : 
  - Supporter les tabulations
  - Permettre de modifier la taille d'une tabulation d'indentation

**Comment by Julien00859** [comment]
Le support des tabs est déjà possible si tu utilises le service via curl
