### ISSUE TITLE
Bootstraping

### ISSUE THREAD

**Issue by Julien00859** [readthedocs-fr/bin-server#4]
Développer les fonctionnalités de bases

**Comment by NoeMastrorillo** [comment]
Ça serait bien de séparer le bootstraping du serveur python et celui du front en html/css/js pour bien avoir les différents contributeurs sur les 2 parties différentes.

**Comment by Julien00859** [comment]
Naaaan, avoir des conflits ça va vous forcer à apprendre git :D (je suis sérieux)

**Comment by Julien00859** [comment]
Puis les fichiers seront séparés, on aura un fichier html dédié, un fichier css dédié, des fichiers js dédiés donc yaura pas de conflit. Faire du inline c'est juste une mauvaise idée x)
