### ISSUE TITLE
Intégration continue

### ISSUE THREAD

**Issue by Julien00859** [readthedocs-fr/bin-server#45]
Dépend de #44 

Afin d'assurer que chaque contribution externe ne casse pas le projet, je propose d'ajouter un mécanisme d'intégration continue via une quelconque technologie (github actions, travis, jenkins, ...) afin de faire passer la batterie de tests unitaires pour chaque nouvelle pull-request.

Vu qu'incorporer un tel outil vient changer le process de développement, un effort devra être fait au niveau soit de la documentation soit de la formation à l'outil.

**Comment by AntoineJT** [comment]
Je pense que GitHub Actions serait très approprié pour ça
