### ISSUE TITLE
Problème de barre horizontale de scroll non souhaitée

### ISSUE THREAD

**Issue by enimaloc** [readthedocs-fr/bin-server#46]
Le scroll de la page ne se fait pas correctement, la numérotation de ligne ne suit pas, [exemple](https://rtdbin.fusetim.tk/arbipp.md)

**Comment by Aakodal** [comment]
Je croyais que #40 avait fixé le truc :eyes:
@fusetim sûr que c'est pas toi qui aurait build une vieille version ou que sais-je ?

**Comment by AntoineJT** [comment]
C'est une vieille version

**Comment by fusetim** [comment]
La version déployée est c00c9ac

**Comment by AntoineJT** [comment]
J'en doute fortement
![image](https://user-images.githubusercontent.com/26577763/101287192-13925280-37ef-11eb-9042-311c668a8372.png)

**Comment by AntoineJT** [comment]
Cela ne peut pas être la version c00c9ac puisque style.css ne correspond pas à ce commit, étant donné que sur la version déployée il y a les lignes encadrées plus haut, alors qu'elle n'y sont plus à partir de ce commit : https://github.com/readthedocs-fr/bin/blob/c00c9acc974be1c01bf8dbaa3448f03a9d53de77/bin/assets/styles/style.css

**Comment by Aakodal** [comment]
C'était un problème avec le cache Cloudflare, je close

**Comment by AntoineJT** [comment]
Je rouvre, il y a bien un problème, même après reload du cache CloudFlare
![image](https://user-images.githubusercontent.com/26577763/101287390-4ee15100-37f0-11eb-8672-e2a50ed0351a.png)

**Comment by Julien00859** [comment]
Hello est-ce que quelqu'un peut vérifier avec #42 que le problème est bien corrigé ?

**Comment by NoeMastrorillo** [comment]
> Hello est-ce que quelqu'un peut vérifier avec #42 que le problème est bien corrigé ?

Yep c'est nickel.
