### ISSUE TITLE
Problem: possible XSS when accessing raw html snippets

### ISSUE THREAD

**Issue by AZ-0** [readthedocs-fr/bin-server#49]
## Reproduce XSS attack
1. Create a snippet containing the following code (the selected language in the dropdown list doesn't matter):
```
<html>
<body>
<script>
alert("XSS");
</script>
</body>
</html>
```

The generated url should look like `https://rtdbin.fusetim.tk/upfila.html`

2. Add `/raw` right after the root: `https://rtdbin.fusetim.tk/raw/upfila.html`
3. Navigate to the new url: you will notice the javascript code is executed
![image](https://user-images.githubusercontent.com/35401882/103007540-e1ddf300-4533-11eb-949c-accbc01a37a7.png)

Anyone that clicks on the raw link will be subject to an XSS attack; while it doesn't matter right now, this could provide attackers with a way to steal sessions or other client side stored data in the future.

## Root of the problem
In `controller.py`, in the `/raw` route, the returned response doesn't contain a `Content-Type` header telling the client browser to interpret data as plaintext.

## Proposed fix
Force `Content-Type` header to the following `text/plain; charset=utf-8`. This should prevent the client browser from blindly interpreting the snippet as a legit html page.

**Comment by Julien00859** [comment]
Hello @AZ-0 thank you for the bug report, would you mind to review the proposed fix ?
