### ISSUE TITLE
Longévité des snippets

### ISSUE THREAD

**Issue by Aakodal** [readthedocs-fr/bin-server#5]
Au lieu de limiter les snippets dans le temps, nous avons décider de limiter la taille de la base de donnée Redis. Ainsi, lorsque l'usage mémoire sera trop conséquent (valeur à déterminer), les snippets peu lus et plus anciens seront supprimés pour laisser place aux nouveaux. Cela sera réalisable grâce au mécanisme LRU de Redis.

Les snippets pourront tout de même avoir une limite de temps choisie par l'utilisateur, qui sera définie par défaut sur 1 semaine, et aussi une limite d'utilisations qui sera par défaut infinie.

À faire : 
- [x] Limite d'utilisation des snippets
- [x] Limite de temps de vie des snippets
- [x] Limite de la taille de la base de données (À faire localement sur la bdd)

**Comment by NoeXWolf** [comment]
On n'avait pas dit ça...

**Comment by NoeMastrorillo** [comment]
On met sur combien la taille maximale de la db ?

**Comment by Julien00859** [comment]
200 Mo ? Ce sera large.

**Comment by NoeMastrorillo** [comment]
Ok de toute façon ça c'est sur la bdd directement qu'il foudra le configurer.

**Comment by Julien00859** [comment]
On peut fournir un fichier de configuration d'exemple avec les instructions sur comment l'utiliser. On peut faire une page dans le wiki pour ça :)

**Comment by NoeMastrorillo** [comment]
Yep ça me serait utile merci 👌
Et aussi faudrait qu'on fixe #19 au plus vite mais j'ai vraiment rien trouvé sur internet.

**Comment by Julien00859** [comment]
Ne pas oublier qu'il faut ajouter un menu dans le frontend pour rendre tout ceci facilement configurable !!

**Comment by Julien00859** [comment]
CC #34

**Comment by NoeMastrorillo** [comment]
J'voulais le faire mais j'ai abandonné j'suis trop nul en front

**Comment by fusetim** [comment]
Ne devrait-on pas fermer cette issue ?

**Comment by Julien00859** [comment]
Il manque l'UI

**Comment by fusetim** [comment]
En effet, je suis passé à côté

**Comment by Julien00859** [comment]
Fixé par #53
