### ISSUE TITLE
Rajouter une utilisation max

### ISSUE THREAD

**Issue by IAMISSAM** [readthedocs-fr/bin-server#66]
Car la redirection à la création d'un bin consomme une utilisation, ca serait bien de rajouter une utilisation quand l'utilisateur en a spécifié une pour que le nombre choisi soit plus cohérent.

**Comment by x0rld** [comment]
il faudrait que ça soit par ip unique parce que si on rechage la page ça foire le truc

**Comment by AntoineJT** [comment]
> Car la redirection à la création d'un bin consomme une utilisation, ca serait bien de rajouter une utilisation quand l'utilisateur en a spécifié une pour que le nombre choisi soit plus cohérent.

Il faudrait plutôt rajouter une utilisation quand le bin a été créé via l'interface web, mais ne pas en ajouter une lorsqu'il a été créé via cURL

**Comment by Julien00859** [comment]
> il faudrait que ça soit par ip unique parce que si on rechage la page ça foire le truc

Pas génial au niveau des RGPD puis si le gars refresh 5x je trouve ça normal que ça consomme 5 utilisations

Edit: [confirmé par Améthyste](
https://www.cnil.fr/fr/ladresse-ip-est-une-donnee-caractere-personnel-pour-lensemble-des-cnil-europeennes)

**Comment by x0rld** [comment]
ok why not c'était juste une idée

**Comment by Julien00859** [comment]
Aussi je précise que le dataset propose déjà `2` dans les suggestions

**Comment by Mesteery** [comment]
Le plus simple, ce serai de pas compter la première visite. Ou bien plus simplement ajouter +1, sauf que faudrait gérer le -1.

**Comment by AntoineJT** [comment]
Si au lieu de mettre 2 utilisations en interne on en met 3, pas besoin de gérer le -1 comme un 0 de façon pas très propre
Il suffirait, quand le bin est créé via l'interface web, de rajouter une utilisation qui serait directement consommée dès la création, via l'accès automatique au bin nouvellement créé.

**Comment by Julien00859** [comment]
Le plus simple c'est de mettre un tooltip d'avertissement lorsque l'utilisateur met 1 dans son interface, voir d'interdire 1 comme valeur

**Comment by Mesteery** [comment]
Je suis d'accord pour une alerte lorsque l'user met 1.
D'ailleurs, 0 est compté comme infinie.

**Comment by Julien00859** [comment]
Interdire 0 dans le front et le back
Avertir pour 1 dans le front

👍 / 👎

**Comment by Julien00859** [comment]
https://github.com/readthedocs-fr/bin/issues/68#issue-780922970

> Si l'on met le minimum de temps et d'utilisation d'un bin à 0 (en prenant en compte le fait que 0 désignerait l'infini), nous n'avons plus de problème entre -1 et 0 pour l'infini.
