### ISSUE TITLE
Sauvegarder un bin avec Ctrl+S

### ISSUE THREAD

**Issue by Linekio** [readthedocs-fr/bin-server#74]
Ça serait bien de pouvoir sauvegarder son bin avec un ctrl+s, qu'en pensez vous ?

**Comment by Kawacrepe** [comment]
Super idée !

**Comment by wyx0-xyz** [comment]
*Ctrl+s

**Comment by WeeskyBDW** [comment]
Voir, en plus, control + S pour les ~~pigons~~ utilisateurs Mac

**Comment by KoukiFactori** [comment]
> Voir, en plus, control + S pour les ~pigeons~ utilisateurs Mac

wowowow déjà c'est Command + S merci
