### ISSUE TITLE
Scroll vertical inutile quand le code dépasse horizontalement

### ISSUE THREAD

**Issue by Mesteery** [readthedocs-fr/bin-server#77]
Du moins sur un téléphone, un scroll vertical apparait inutilement, quand le code dépasse la page horizontalement (il y a un scroll horizontal, mais ca c'est normal).

https://bin.readthedocs.fr/ableni.txt :
![Useless vertical scroll](https://user-images.githubusercontent.com/48163546/104773735-ce5e2a80-5775-11eb-916f-db62e9486326.png)

**Comment by Mesteery** [comment]
Une solution serait de word-break :
```diff
diff --git a/bin/assets/styles/style.css b/bin/assets/styles/style.css
index eaa409f..0645ee3 100644
--- a/bin/assets/styles/style.css
+++ b/bin/assets/styles/style.css
@@ -26,18 +26,14 @@ body {
     background: transparent !important;
     font-family: Consolas, monospace;
     font-size: 1em;
-    overflow-x: scroll;
     border-spacing: 0;
     border-collapse: separate;
 }

-tr, td {
-    vertical-align: baseline;
-    white-space: pre;
-}
-
 .line-content {
-    padding: 0 0 0 0.5em;
+    padding: 0.5em;
+    border-radius: 2.5px;
+    word-break: break-all;
 }

 .line-content.selected {
 ```
Résultat :
![image](https://user-images.githubusercontent.com/48163546/106390099-0d7fb300-63e7-11eb-9eb0-d6930784682a.png)

**Comment by Julien00859** [comment]
Peut-être est-ce qu'on devrait se poser des questions fondamentales d'UI sur phone ?

**Comment by Mesteery** [comment]
Ici ce n'est pas forcement que sur téléphone, c'est pas un problème d'UI mais bel et bien d'un bug (a cause de moi). Il peut aussi être présent sur des écrans de petites tailles, comme des tablettes, ou des petits écrans (ordinateurs portables, etc.)

**Comment by Julien00859** [comment]
J'ai peur qu'en activant le word-wrap ça rende vraiment n'imp sur phone

**Comment by Mesteery** [comment]
Oui, je suis totalement d'accord, le wrap, est horrible que ce soit sur petit ou grand écran.
C'est une mauvaise solution.
Donc si quelqu'un sait comment fixer ça (faut correctement styliser le `table` pour pas qu'il 
"déborde" de la mauvaise manière)

**Comment by Mesteery** [comment]
C'est pas un petit bug, mais un gros problème de responsivité, le rendu peut vraiment être horrible :
![Screenshot_20210211-100854_Chrome](https://user-images.githubusercontent.com/48163546/107618100-4cb4cc00-6c51-11eb-9108-41652e523b3a.jpg)

**Comment by fusetim** [comment]
As-tu pensé à vider le cache ?

**Comment by Mesteery** [comment]
Il n'y aucune raison pour que ça provienne du cache. Le CSS est à jour (la preuve sur l'image).

**Comment by fusetim** [comment]
On ne sait jamais, personnellement j'ai un rendu acceptable ![Screenshot_2021-02-11-10-13-25-776_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/62183512/107618477-e9776980-6c51-11eb-8466-55534015933d.jpg)

**Comment by fusetim** [comment]
Ah oui non, effectivement le rendu est bon uniquement à l'emplacement d'origine :confused:

**Comment by Mesteery** [comment]
Oui, c'est le problème, on dirait que la page est zoomé.
