### ISSUE TITLE
Implémentation de la coloration syntaxique (highlight.js)

### ISSUE THREAD

**Issue by Aakodal** [readthedocs-fr/bin-server#8]
Les snippets seront colorés d'une manière élégante pour améliorer leur lisibilité. Cette coloration syntaxique se fera grâce à la librairie **highlight.js** et en fonction du langage choisi par l'utilisateur lors de la création du snippet.

**Comment by Julien00859** [comment]
Qu'est-ce qu'il reste à implémenter pour cette feature ?

**Comment by NoeMastrorillo** [comment]
Rien il me semble, tu peux close
