### ISSUE TITLE
Sur mobile, accéder à une page télécharge le fichier plutôt que de l'afficher

### ISSUE THREAD

**Issue by QuentinBubu** [readthedocs-fr/bin-server#81]
Salut,
Petites suggestion, faire en sorte de mettre le code dans un fichier html par exemple, car, avec les fichiers txt notamment, le navigateur nous les téléchargent au lieu de nous afficher le code dans le navigateur du fait de l'extension

**Comment by Julien00859** [comment]
Bonjour Quentin, merci pour ton intérêt pour notre produit !

Je ne comprend pas exactement le problème que tu décris, nous définissons le header http `Content-Type: text/html` lorsque tu accèdes à un snippet sur la route normale et le header http `Content-Type: text/plain` lorsque tu accèdes à la route /raw/. Normalement ton navigateur doit suivre cette directive en priorité de l'extension de la page.

Chez moi sur Firefox 83.0 (64 bits) sur Linux Mint 20 Ulyana, les deux pages suivantes m'affichent 1 paragraphe de lipsum directement dans mon navigateur (je n'ai aucune popup pour me proposer de télécharger un quelconque fichier).

<https://bin.readthedocs.fr/gondan.txt>

![2021-01-22_02-38-01](https://user-images.githubusercontent.com/8208953/105433969-f14b7b80-5c5a-11eb-89e8-6b592a084575.png)

<https://bin.readthedocs.fr/raw/gondan.txt>

![2021-01-22_02-38-13](https://user-images.githubusercontent.com/8208953/105433970-f1e41200-5c5a-11eb-8ab6-283a12954382.png)

Quel système et quel navigateur utilises-tu ? Est-ce que les deux pages ci-dessus s'ouvrent bien directement dans ton navigateur, qu'aucun fichier ne se télécharge ?

**Comment by Julien00859** [comment]
Si le problème affecte des vieux navigateurs ou des appareils mobiles, on peut peut-être faire comme tu suggères, remplacer l'url par `/gondan.html?lang=text` si on détecte un vieux navigateur tout pourri via le header User-Agent.

**Comment by KoukiFactori** [comment]
Hello,
J'ai testé de mon côté et je n'ai pas rencontré ce soucis sur les navigateurs que j'ai.

Build de Windows: Windows 10 20H2 19042

Chrome: `87.0.4280.141` et `88.0.4324.104`
Edge (Chromium): `87.0.664.75`
Firefox: `81.0.2`

**Comment by QuentinBubu** [comment]
Sur ordinateur, comme dis c'est une vielle version avec win xp et chrome 20 et quelques... _oui oui, il y a encore des gens avec x)_ et du coup ça m'ouvre la page puis la referme en téléchargent le fichier.
Le plus embêtant c'est vraiment sur mobile ça le télécharge aussi, comme sur pc, ça ouvre le navigateur puis le referme et télécharge le fichier

Version Android: 8.0.0
Version Chrome: 88.0.4324.93

**Comment by Julien00859** [comment]
Pour Windows ok, ce n'est pas un problème, voila plusieurs années que Microsoft a arrêté le support pour leur ancien OS voir https://docs.microsoft.com/en-us/lifecycle/products/windows-xp . On ne fixera pas le problème.

Pour Android c'est plus embêtant, on va voir ce qu'on peut faire.

**Comment by Mesteery** [comment]
Bonjour,
J'ai exactement la même version de Chrome Android que toi et je n'ai pas du tout ce problème. 
Cela vient sûrement de tes paramètres.

**Comment by QuentinBubu** [comment]
Oui en effet, voyant que chez Nolan, ca ne le fait pas non plus, je me suis penché d'un peu plus près aux paramètres et j'ai modifié un truc _je ne saurais vous dire lequel_ et maintenant ça ne me télécharge plus les txt.
Désolé du dérangement

**Comment by Julien00859** [comment]
Pas de problème, je ferme donc l'issue comme il s'agit d'une "simple" mauvaise configuration du navigateur.
