### ISSUE TITLE
Faire que discord ne consomme pas des utilisations

### ISSUE THREAD

**Issue by Julien00859** [readthedocs-fr/bin-server#91]
Lorsque le lien d'un bin est partagé sur discord, discord fait des requêtes GET gratuites pour prévisualiser le contenu de la page. Ce serait bien que discord ne consomme pas des *maxusage*.

**Comment by fusetim** [comment]
Est ce que blacklist les bots dans un robots.txt réglerait le problème ?

**Comment by nathan-trioleyre** [comment]
Faudrait juste pas incrémenter lorsque que c'est discord qui fait la requête

**Comment by AntoineJT** [comment]
Yep, je peux m'en occuper mais il me faudrait plus d'infos sur la requête que discord envoie au serveur (IP, ou headers spécifiques, etc.)
La gestion des vues restantes est effectuée ici : https://github.com/readthedocs-fr/bin/blob/main/bin/models.py#L45

**Comment by Mesteery** [comment]
Je te dit ça de suite.

**Comment by Mesteery** [comment]
```js
{
  connection: 'close',
  'x-forwarded-for': '35.227.62.178,::ffff:10.10.11.119,::ffff:10.10.90.120',
  'x-forwarded-proto': 'https,http,http',
  'x-forwarded-port': '443,80,80',
  host: 'xx',
  accept: '*/*',
  'user-agent': 'Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com)',
  'x-forwarded-host': 'xx',
  traceparent: '00-6ba8a733e22949cdab3b1d4ebe590622-5fab2c68da123a0c-01'
}
```
UserAgent: `Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com)`
IP: `35.227.62.178`

Se baser sur l'user-agent ne serait pas fiable. L'IP a l'air d'être tout le temps la même, mais ca reste a vérifier.

**Comment by Mesteery** [comment]
J'ai vérifier et l'IP n'est pas toujours la même suivant la région j'imagine : `35.237.4.214`.

**Comment by AntoineJT** [comment]
Je ne peux décidément pas matcher sur l'user-agent, des gens pourraient l'utiliser pour que leurs vues ne soient pas comptabilisées, et je ne pense pas que ce soit une bonne idée.
Récupérer toutes les IP utilisées par Discord et mettre à jour cette liste risque d'être fastidieux et à terme il pourrait y avoir des IP dans la whitelist qui n'appartiendraient plus à Discord.
Du coup, je ne vois pas trop comment faire pour implémenter ça correctement

**Comment by Mesteery** [comment]
Apres beaucoup de tentatives avec toutes les régions possibles, voici les seules IP qui ressortent : `35.237.4.214`, `35.196.132.85` et `35.227.62.178`. Elles sont tous détenus par Google Cloud.

**Comment by Mesteery** [comment]
```
35.237.4.214
35.196.132.85
35.227.62.178
35.229.59.108
35.190.167.223
35.237.116.125
35.196.167.40
35.196.75.24
35.196.227.176
35.231.187.179
```
Une liste beaucoup plus exhaustive *(merci https://udger.com/resources/ua-list/bot-detail?bot=Discordbot)*.

**Comment by DeltaEvo** [comment]
Une bonne solution je penses est de matcher sur l'user agent mais de ne pas envoyer le contenu du bin dans ce cas, juste le head pour que le crawler fasse l'embed

Et ça vaudrai le coup d'ajouter plus que discord
https://github.com/monperrus/crawler-user-agents
