### ISSUE TITLE
Ajout de Scala dans highlights.py

### ISSUE THREAD

**Issue by Iltotore** [readthedocs-fr/bin-server#94]
Le titre dit tout: ceci est une suggestion pour ajouter le langage [Scala](https://scala-lang.org) au projet.

**Comment by Mesteery** [comment]
https://github.com/readthedocs-fr/bin-server/blob/main/bin/highlight.py#L36.
C'est juste que la version en ligne n'est pas tout à fait à jour.

**Comment by fusetim** [comment]
Oui en effet, le support est là, mais il n'a pas encore été déployé sur https://bin.readthedocs.fr
Toutefois, il marche, tu peux l'essayer ici : https://rtdbin.fusetim.tk/ndwook.scala (version: af67cfa).
(il sera peut-être nécessaire de vider le cache pour le voir)

**Comment by Julien00859** [comment]
Voila, le serveur a été mis à jour sur la dernière main <https://bin.readthedocs.fr/oxialo.scala>
