### ISSUE TITLE
Possibilité de supprimer son bin.

### ISSUE THREAD

**Issue by TNtube** [readthedocs-fr/bin-server#98]
Une feature intéressante serait que, au moment du post d'un nouveau bin, l'auteur reçoive un code qu'il peut mettre de côté afin de pouvoir supprimer à tout moment le contenue du bin.

**Comment by Julien00859** [comment]
Il y a plusieurs problèmes relatifs à cette tâche qui font que ça va être très difficile à faire.

Pour commencer il faut savoir qu'il n'y a pas de compte utilisateur, nous ne gardons dans la base de donnée aucune information relatif à l'auteur d'un snippet. Nous ne voulons pas d'un système de compte car nous estimons que `bin` sert uniquement à vite fait partager un petit snippet de code, l'intérêt à avoir un compte pour lister "ses" snippets est assez limité et correspond plus à d'autres plateformes comme gist.

Du fait qu'il n'y a pas de compte, les autres techniques qui consisteraient à identifier un utilisateur seraient l'adresse IP (non fiable en réseau mobile) ou bien des cookies de navigation (impossible à utiliser dans un terminal et la question soulève des questions éthique de respect de la vie privée, coucou cnil, coucou rgpd).

Comme nous ne voulons pas laisser de trace persistante qui permettrait d'identifier un utilisateur, la dernière possibilité serait de permettre uniquement à celui qui sauvegarde un snippet de le supprimer *uniquement* lors de la première visite. Ici nous rentrons dans une limitation technique, lorsqu'un utilisateur a sauvegardé un snippet il ne reçoit pas immédiatement le content sauvegardé. Au lieu de ça, le serveur lui envoie une redirection vers l'url qui permette d'afficher le snippet afin de remplir l'url dans le navigateur directement avec le lien à copier/coller. Du fait de la redirection, le navigateur jette complètement l'ancienne requête pour en démarrer un nouvelle neuve. Sans persistance de donnée (cookie/compte), impossible de renvoyer un moyen à l'auteur de supprimer son code.

Au vu des considérations ci-dessus, je pense qu'il est malheureusement impossible d'implémenter cette fonctionnalité.

**Comment by Aakodal** [comment]
Tu n'as rien dit concernant *sa* proposition, à savoir un code généré lors de la création du bin, un peu comme un rescue code, qui permettrait de le supprimer une fois rentré

**Comment by Mesteery** [comment]
Alors si, il y a une bonne solution.
Au moment de la création du bin, un token "admin" pourrait être créé et affiché au créateur. 
Grâce à ce token "admin", le créateur peut supprimer son bin à tout miment.

**Exemples :**
* un bin est créé, et il est redirigé, un token "admin" est affiché, l'utiliser le sauvegarde.
* un autre jour, cet utilisateur décide de supprimer son bin :
  * soit il va sur `<domain>/tYziin.ts?token=<myAdminToken>` et appuie sur un bouton pour supprimer (uniquement présent s'il y  a un token valide).
  * soit `DELETE <domain>/tYziin.ts` accompagné du token, soit dans l'url (`?token=<myAdminToken`) soit dans un form, par exemple ou via le header `Authorization`.

Au moment de la création, le token "admin" pourrait également être transmis via un header.

**Comment by Julien00859** [comment]
D'accord, comment on affiche le token au créateur ?

**Comment by Mesteery** [comment]
1. via la réponse : *Au moment de la création, le token "admin" pourrait également être transmis via un header.*
2. pour le front, le token pourrait être affiché via une popup, par exemple (seulement au premier chargement bien évidemment)

**Comment by Julien00859** [comment]
Tu me fais penser à qqch

1. Toujours générer un nouveau token lorsque l'utilisateur récupère le formulaire original (le mettre dans un champ invisible)
2. Mettre le token dans le localstorage de l'utilisateur, vu que c'est une info générée et non retransmise ya aucun problème niveau cnil/rgpd
3. Récupérer ce token avec la soumission du formulaire, l'enregistrer dans redis
4. Ajouter une URL pour supprimer via le token le snippet 

Ça va demander une petite réflexion niveau UI pour supprimer un token, on peut peut-être garder ça simple : "si il existe un token de suppression pour le snippet actuel => afficher un bouton de suppression"

Pour les outils externes, vu qu'ils ne récupèrent pas le formulaire (ils ne font pas de `GET /`) ils devront remplir le champ token eux-même et l'intégrer à leur service à leur manière. Pour curl on pourrait très bien *ne pas* remplir le champ, le snippet serait impossible à delete mais en ligne de commande tu t'en fous un peu. Pour discord, le bot pourrait générer un token et associer l'envoie du token (=la suppression du snippet) au fait que l'auteur original du message réagisse avec un :wastebasket:
