### ISSUE TITLE
Support du Drag&Drop

### ISSUE THREAD

**Issue by fusetim** [readthedocs-fr/bin-server#99]
L'ajout du drag&drop de fichier sur l'interface Web semble une feature à envisager.
Cela demandera sûrement quelques efforts sur le front.

**Comment by Mesteery** [comment]
C'est très facile à faire, tu veux t'en occuper ?

**Comment by AntoineJT** [comment]
Je voulais bien m'en occuper, mais je laisse ma place à Tim s'il désire le faire : après tout, c'est son idée

**Comment by Mesteery** [comment]
*Moi aussi je voulais bien m'en occuper, mais du coup ce sera un de vous deux finalement 😅*

**Comment by Mesteery** [comment]
Je propose qu'on laisse le comportement par défaut s'il y a plusieurs fichiers/dossiers ou si c'est un fichier binaire (notamment détectable via le type MIME ou l'extension).
Dans le cas contraire, nous pouvons simplement afficher le contenu du fichier dans la textarea, et bien évidemment mettre le bon langage. L'utilisateur pourra donc visualiser son fichier, et pourra soumettre comme d'habitude, comme il le ferai sans DragnDrop.

**Comment by fusetim** [comment]
Vous pouvez faire des implés si vous voulez, je suis pas sûr d'avoir les compétences nécessaires pour faire un truc propre la dessus

**Comment by Mesteery** [comment]
C'est pas grave, tu peux toujours essayer, dans tous les cas, nous sommes là pour te guider et t'aider.
